version: '2'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - NODE_ENV
      - BUCKET_MARKDOWN
      - STAGE
      - FAKES3_PORT
      - API_ENDPOINT
    links:
      - fakes3
    volumes:
      - ./:/app
    command: serverless offline --host 0.0.0.0

  fakes3:
    image: lphoward/fake-s3

  fakes3boostrap:
    build: .
    links:
      - fakes3
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - BUCKET_MARKDOWN
    depends_on:
      - fakes3
    command: bash -c 'node ./fakes3/bootstrap.js'

  test:
    build: .
    links:
      - api
    depends_on:
      - api
    volumes:
      - ./tests:/app/tests
    command: bash -c "sleep 5s && mocha tests/integration --timeout 5000"
