service: vellm-api

provider:
  name: aws
  runtime: nodejs4.3
  region: ${env:AWS_REGION}
  stage: ${env:STAGE}
  environment:
    BucketName: ${env:BUCKET_MARKDOWN}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  vellums_get:
    handler: functions/vellums.get
    events:
      - http:
          path: users/{user}/vellums/{vellum}
          method: get
          integration: lambda
          request:
            parameters:
              paths:
                user: true
                vellum: true

resources:
  Resources:
    markdown:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${env:BUCKET_MARKDOWN}

plugins:
  - serverless-offline
